### ISSUE TITLE
Resolve issue with incorrect normals in ClipperOffset

### ISSUE THREAD

**Issue by drlukeparry** [drlukeparry/pyclipr#4]
Normals are incorrect when performing an offset using `ClipperOffset` using the `EndType.Polygon` for the added paths.

**Comment by cpmessina** [comment]
I'm having in issue with ClipperOffset that the hole polygons are offsetting the same direction as the outer polygon (using a negative offset, the outer insets properly, but the holes also inset instead of outset).

Is this the same issue as what you're referring to with incorrect normals?

**Comment by drlukeparry** [comment]
The instance is you need to use addPaths for each polygon, rather than individual addPath. This is normally. unrelated to the windings/orientation of the paths in the polygons passed to ClipperOffset.

I have an internally made a fix based on this knowledge and consulting with Angus on ClipperLib. I plan to incorporate the changes soon but been relatively busy with work.
